clc; clear all; close all;

data = importfile("csv\DrawingTest1.csv", [1, Inf]);

figure;
plot(data.traj1, data.traj2, data.input1, data.input2)
legend("Desired Trajectory", "User Input")



function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  DATA = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  data = importfile("C:\Users\Kyle\OneDrive - UW\Documents\GitHub\hebi_arm\csv\DrawingTest1.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Oct-2021 14:43:00

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t", "traj1", "traj2", "input1", "input2"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

end